services:
  - type: web
    name: deepshield-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true

  - type: web
    name: deepshield-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build